version: 2
updates:
- package-ecosystem: pip
  directory: /ci/scripts
  schedule:
    # Check for updates every weekday
    interval: "daily"
    time: "06:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "ci"
  labels:
    - run-ci
- package-ecosystem: gomod
  directory: /src/pcap
  schedule:
    # Check for updates every weekday
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "dep"
  labels:
    - run-ci
- package-ecosystem: gomod
  directory: /acceptance-tests
  schedule:
    # Check for updates every weekday
    interval: "daily"
    time: "18:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "dep"
  labels:
    - run-ci
